--- ## GATEWAY
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kupcr.fullname" . }}-gateway
  labels:
    component: gateway
{{ include "kupcr.labels" . | indent 4 }}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    - port: {{ .Values.gateway.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "kupcr.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: gateway

--- ## FLOWER
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kupcr.fullname" . }}-flower
  labels:
    component: flower
{{ include "kupcr.labels" . | indent 4 }}
spec:
  type: {{ .Values.flower.service.type }}
  ports:
    - port: {{ .Values.flower.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "kupcr.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: flower
