apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kupcr.fullname" . }}-web
  labels:
    component: web
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kupcr.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kupcr.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: web
    spec:
      containers:
        - name: {{ .Chart.Name }}-web
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: '{{ template "kupcr.fullname" . }}-env'
          command: ["uvicorn"]
          args:
            - "{{ .Values.web.app }}"
            - '--workers'
            - '{{ .Values.web.threads }}'
            - '--log-level'
            - 'error'
          ports:
            - name: http
              containerPort: {{ .Values.web.service.port }}
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /ping
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /ping
#              port: http
          resources:
{{ toYaml .Values.web.resources | indent 12 }}
    {{- with .Values.web.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.web.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.web.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}

--- # Horizontal Pod Autoscaler
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "kupcr.fullname" . }}-web-scaler
  labels:
    component: web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "kupcr.fullname" . }}-web
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60