apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kupcr.fullname" . }}-web
  labels:
    component: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kupcr.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kupcr.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: web
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: {{ .Chart.Name }}-web
          #image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: '{{ template "kupcr.fullname" . }}-env'
          command: ["uvicorn"]
          args:
            - "{{ .Values.web.app }}"
            - '--workers'
            - '{{ .Values.web.threads }}'
          ports:
            - name: http
              containerPort: {{ .Values.web.service.port }}
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /ping
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /ping
#              port: http
          resources:
{{ toYaml .Values.web.resources | indent 12 }}
    {{- with .Values.web.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.web.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.web.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
