apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kupcr.fullname" . }}-worker
  labels:
    component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kupcr.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kupcr.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: worker
    spec:
      serviceAccountName: {{ .Values.worker.k8sSvcAccount }}
      terminationGracePeriodSeconds: 1
      containers:
        - name: {{ .Chart.Name }}-worker
          #image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: "{{ template "kupcr.fullname" . }}-env"
          command: ["celery"]
          args:
            - 'worker'
            - '-A'
            - "{{ .Values.worker.app }}"
            - '--concurrency={{ .Values.worker.threads }}'
          resources:
{{ toYaml .Values.worker.resources | indent 12 }}
    {{- with .Values.worker.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.worker.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.worker.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
