apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ReactiveSQL.fullname" . }}-flower
  labels:
    component: flower
{{ include "ReactiveSQL.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount.flower }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ReactiveSQL.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: flower
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ReactiveSQL.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: flower
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: {{ .Chart.Name }}-flower
          #image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          image: "{{ .Values.image.repository }}:1.0"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["flower"]
          args:
            - '--broker'
            - 'redis://myrx-reactivesql-redis:6379/0'
            - '--port=80'
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
