apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ReactiveSQL.fullname" . }}-redis
  labels:
    component: redis
{{ include "ReactiveSQL.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ReactiveSQL.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ReactiveSQL.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: redis
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: {{ .Chart.Name }}-redis
          image: "redis"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 6379
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
