apiVersion: v1
kind: Service
metadata:
  name: {{ template "ReactiveSQL.fullname" . }}-web
  labels:
    component: web
{{ include "ReactiveSQL.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.web.type }}
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "ReactiveSQL.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: web
