apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ReactiveSQL.fullname" . }}-worker
  labels:
    component: worker
{{ include "ReactiveSQL.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount.prestoWorker }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ReactiveSQL.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ReactiveSQL.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: worker
    spec:
      containers:
        - name: {{ .Chart.Name }}-worker
          #image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          image: "{{ .Values.image.repository }}:1.0"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["celery"]
          args:
            - '-A'
            - 'app.prestoWorker'
            - 'worker'
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
