apiVersion: v1
kind: Service
metadata:
  name: {{ template "kupcr.fullname" . }}-redis
  labels:
    component: redis
{{ include "kupcr.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.redis.type }}
  ports:
    - port: {{ .Values.service.redis.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "kupcr.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: redis
